name: Trigger auto deployment for container-app-t7k6lawpetgyg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-t7k6lawpetgyg-AutoDeployTrigger-5315a222-7350-41a4-b569-a9f2e247fe8e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPT7K6LAWPETGYG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPT7K6LAWPETGYG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPT7K6LAWPETGYG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPT7K6LAWPETGYG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPT7K6LAWPETGYG_REGISTRY_PASSWORD }}
          containerAppName: container-app-t7k6lawpetgyg
          resourceGroup: todonodejspgsqlgoogleautha7e98075
          imageToBuild: default/container-app-t7k6lawpetgyg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


